#!/bin/sh
set -e

dpkg-maintscript-helper mv_conffile /etc/php5/conf.d/ffmpeg.ini /etc/php5/mods-available/ffmpeg.ini 0.6.0-2.1 -- "$@"

[ "$1" = "remove" ] && echo "Disable ffmpeg module manually."

#DEBHELPER#

exit 0
